### ISSUE TITLE
Saving a Design

### ISSUE THREAD

**Issue by kadnan** [Wicklers/Tee-Designer#2]
Loved your script. Main thing is that it's just interface editor. A few questions:
- What if I want to change the base t-Shirt, how do I do it? can  just put any image?
- How to add products like full sleeves tshirts etc?
- How to Save product information including coordinates into Database?

Thanks

**Comment by harshvladha** [comment]
Hello Kadnan,

Currently, this Plugin just supports Image creation from the HTML5 canvas.
Also, you can check out image directory where we have added **base** tshirt which you can replace with your **base-style** of the t-shirt.

Hope this helps.

**Comment by kadnan** [comment]
Thanks

Guess you forgot to answer last 2 points

**Comment by Yogi1994** [comment]
Hello Adnan,

*Answer 1: *
 If you want *to replace base tee with your own*, then simply *replace the
tee-shirts* or hoodies* in * /tdesignAPI
<https://github.com/2Wicklers/Tee-Designer/tree/master/tdesignAPI>/images
<https://github.com/2Wicklers/Tee-Designer/tree/master/tdesignAPI/images>/
*product*/  direcrory.

*Answer 2:*
If you want* to add the new type of products* then go to *line number 39*
 in  /tdesignAPI
<https://github.com/2Wicklers/Tee-Designer/tree/master/tdesignAPI>/js
<https://github.com/2Wicklers/Tee-Designer/tree/master/tdesignAPI/js>/
*mainapp.js*  file in any text editor and add new products accordingly.
Also, open   /tdesignAPI
<https://github.com/2Wicklers/Tee-Designer/tree/master/tdesignAPI>/*new_applit.php
  * open file in any text editor at line number 82 add radio button 4,5,6
according to your need.

*Answer 3:*
This you have to implement by yourself. We have not yet implemented this.
Read about HTML5 Canvas. Line number 307 to 365 is HTML form used to submit
the data.

*NOTE: To add a new product or replace the previous one go to line number
5 in  /tdesignAPI
<https://github.com/2Wicklers/Tee-Designer/tree/master/tdesignAPI>/js
<https://github.com/2Wicklers/Tee-Designer/tree/master/tdesignAPI/js>/mainapp.js
file and read the line. You will understand the directory format and names
to be given for the products.*


Regards,


*Yogesh Chauhan*
*Convener - TechnoPark <http://www.technopark.co>*
Computer Science and Engineering - 2016 (B.Tech)
National Institute of Technology, Silchar <http://www.nits.ac.in>
Mobile: +91 8402059135
Linkedin <http://in.linkedin.com/in/yogeshchauhan1> | 2wicklers Blog
<http://www.2wicklers.com> | Github Profile <https://github.com/Yogi1994>

**Comment by Yogi1994** [comment]
Hello Adnan,

*Answer 1: *
 If you want *to replace base tee with your own*, then simply *replace the
tee-shirts* or hoodies* in * /tdesignAPI
<https://github.com/2Wicklers/Tee-Designer/tree/master/tdesignAPI>/images
<https://github.com/2Wicklers/Tee-Designer/tree/master/tdesignAPI/images>/
*product*/  direcrory.

*Answer 2:*
If you want* to add the new type of products* then go to *line number 39*
 in  /tdesignAPI
<https://github.com/2Wicklers/Tee-Designer/tree/master/tdesignAPI>/js
<https://github.com/2Wicklers/Tee-Designer/tree/master/tdesignAPI/js>/
*mainapp.js*  file in any text editor and add new products accordingly.
Also, open   /tdesignAPI
<https://github.com/2Wicklers/Tee-Designer/tree/master/tdesignAPI>/*new_applit.php
  * open file in any text editor at line number 82 add radio button 4,5,6
according to your need.

*Answer 3:*
This you have to implement by yourself. We have not yet implemented this.
Read about HTML5 Canvas. Line number 307 to 365 is HTML form used to submit
the data.

*NOTE: To add a new product or replace the previous one go to line number
5 in  /tdesignAPI
<https://github.com/2Wicklers/Tee-Designer/tree/master/tdesignAPI>/js
<https://github.com/2Wicklers/Tee-Designer/tree/master/tdesignAPI/js>/mainapp.js
file and read the line. You will understand the directory format and names
to be given for the products.*


Regards,


*Yogesh Chauhan*
*Convener - TechnoPark <http://www.technopark.co>*
Computer Science and Engineering - 2016 (B.Tech)
National Institute of Technology, Silchar <http://www.nits.ac.in>
Mobile: +91 8402059135
Linkedin <http://in.linkedin.com/in/yogeshchauhan1> | 2wicklers Blog
<http://www.2wicklers.com> | Github Profile <https://github.com/Yogi1994>

**Comment by Yogi1994** [comment]
Hello Adnan,

Answer 1: 
 If you want **to replace base tee with your own**, then simply **replace the tee-shirts** or hoodies in  **/tdesignAPI/images/product/**  directory.

Answer 2:
If you want to add the new type of products then go to line number 39 in  /tdesignAPI/js/mainapp.js  file in any text editor and add new products accordingly. Also, open   **/tdesignAPI/new_applit.php**    open file in any text editor at **line number 82 add radio** button 4,5,6 according to your need.

Answer 3:
This you have to implement by yourself. We have not yet implemented this. Read about HTML5 Canvas. **Line number 307 to 365 is HTML form used to submit the data**. 

**NOTE: To add a new product or replace the previous one go to line number 5 in  /tdesignAPI/js/mainapp.js  file and read the line. You will understand the directory format and names to be given for the products.**

**Comment by kadnan** [comment]
Awesome. If implemented successfully, I'd fork it and submit my PR.

**Comment by harshvladha** [comment]
Thank You Kadnan :+1:
