### ISSUE TITLE
Hy Sam, message me. I worked on this project too and I've completed it.

### ISSUE THREAD

**Issue by Anastaufan** [Wicklers/Tee-Designer#8]
Hi ajadi, I have same a problem, however I tried to make checkout with database function and did not working, please show me if you finished this project, I thanks and appreciate you.

**Comment by haseenaL** [comment]
I want to add extra images along with that tee and hoodies. In which folder I have to insert the iamges.

**Comment by Yogi1994** [comment]
@haseenaL I am following a self-made convention here to include the new set of product.
You will need to add a few lines of code inside [this](https://github.com/Wicklers/Tee-Designer/blob/cd884052415ad3c3a885c687b8c9ab66ff9085df/tdesignAPI/new_applit.php#L80) block. 
And then go to the folder giving inside features section 6th point given in the Readme file.
`https://github.com/Wicklers/Tee-Designer#features`.
`Tee-Designer/tdesignAPI/images/product/`  Here you need to add your folder and follow the name convention just like I did for `Hoodie` and `tee`.
